name: Mitrebox
favicon: null
layout_spectrum: 0.75156
typography_spectrum: 0.37651
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
